### PR TITLE
Let's complete it!

### PR DESCRIPTION
**Pull request by ghost**
Here are much changes to complete it (at least almost).

### CODE REVIEW

**Comment by ghost** [comment]
Dirty, hehe :P

**Comment by andrewbanchich** [comment]
Thank you so much @manudinath ! This looks great.

The only question I have is - what's the purpose of the `webrick` dependency [here](https://github.com/manudinath/stellar-jekyll-theme/blob/master/stellar_jekyll_theme.gemspec#L17)?

**Comment by ghost** [comment]
Starting from Ruby 3, if I remembered correctly, webrick has been removed from default dependencies of Gem. In Jekyll 4 this becomes an error. See the issue reference: https://github.com/jekyll/jekyll/issues/8523

**Comment by andrewbanchich** [comment]
Gotcha, thank you!

**Pull request merged**
